#!/usr/bin/env python3
import sys; sys.dont_write_bytecode = True
"""Creates a new, empty private vault outside this repository.

Usage: python3 _system/init_vault.py --destination /Volumes/PrivateNAS/SecondBrain

What it does:
  - Refuses a destination inside this repository's own working tree, or one
    that already exists and is not empty.
  - Creates the standard folder layout (Properties/, Tenants/, Finance/,
    Taxes/, Maintenance/, Legal/, Property Management/, Co-Owners/,
    Documents/{Leases,Invoices,Handover,Tax,Identity}, _system/, Archive/).
  - Copies AGENTS.md, CLAUDE.md, and the templates and scripts under
    _system/, but never the example notes: a real vault starts with empty
    Properties/, Tenants/, and Finance/ folders, not fictional data to
    delete later.
  - Writes fresh NOW.md and _index.md (no placeholder example catalog).
  - Writes a .sensitive-vault marker file (see SECURITY.md and
    docs/AGENT_PERMISSIONS.md for what tooling is meant to do with it).
  - Sets restrictive permissions where the OS supports it (owner-only);
    this is a best-effort convenience, not the security boundary. The
    security boundary is your OS user/ACL setup, see docs/NAS_SETUP.md.
  - Does NOT create a git repository. See SECURITY.md's Git section for
    why, and what to do instead if you want version history.
  - Warns if the destination path looks like it sits inside a well-known
    cloud-sync folder (Dropbox, OneDrive, Google Drive, iCloud Drive):
    this is a heuristic, string-matched on the path, not a guarantee.
  - Validates the result before reporting success.

This script only ever writes into an empty destination it just created.
It never touches this repository, and it never reads or copies any of the
fictional example notes shipped alongside it.
"""
import argparse
import os
import re
import stat
import sys
from pathlib import Path

_DATE_FIELD_RE = re.compile(r"^(created|modified|last_verified): \d{4}-\d{2}-\d{2}$",
                             re.MULTILINE)


def _restamp_dates(text: str, today: str) -> str:
    """Rewrites created/modified/last_verified in a copied file's frontmatter
    to today's date, so a freshly initialized vault starts lint-clean instead
    of immediately reporting the shipped template's own dates as overdue."""
    return _DATE_FIELD_RE.sub(lambda m: f"{m.group(1)}: {today}", text)

REPO_ROOT = Path(__file__).resolve().parent.parent
SYSTEM_SRC = REPO_ROOT / "_system"

CLOUD_SYNC_MARKERS = (
    "dropbox", "onedrive", "google drive", "googledrive",
    "icloud drive", "icloud~", "box sync", "box-sync",
)

DIRS = [
    "Properties", "Tenants", "Finance", "Taxes", "Maintenance", "Legal",
    "Property Management", "Co-Owners", "Archive", "_system",
    "Documents/Leases", "Documents/Invoices", "Documents/Handover",
    "Documents/Tax", "Documents/Identity",
]

SCRIPT_FILES = ["vaultlib.py", "lint.py", "build_export.py",
                 "Template - Property.md", "Template - Tenant.md",
                 "Communication Preferences.md"]

MARKER_CONTENT = """# This file marks this directory as a private, sensitive Second Brain vault.
# Tooling (lint.py, build_export.py) may look for this file before treating
# a --vault path as real, see SECURITY.md. It intentionally contains no
# sensitive data itself.
classification = "sensitive"
cloud_access = "forbidden"
network_egress = "forbidden"
exports = "private-by-default"
"""

FRESH_NOW_MD = """---
description: Rolling log of what is active right now. Keep it under 30 days.
created: {today}
modified: {today}
last_verified: {today}
review: monthly
status: active
area: System
aliases: []
tags: [meta]
---

# NOW

## Active

## Recent developments

## Upcoming

## Open questions
"""

FRESH_INDEX_MD = """---
description: Vault map. Who owns this portfolio in one paragraph plus a catalog of every note with its description.
created: {today}
modified: {today}
last_verified: {today}
review: monthly
status: active
area: System
aliases: [Index, Vault Map]
tags: [meta]
---

# Vault Index

[Replace this paragraph with one or two sentences about your own portfolio: who owns it, how many units, where.] This vault is a local-only, tool-agnostic knowledge base for managing that portfolio, read exclusively by AI models running on your own hardware. Rules: [[AGENTS]]. Current focus: [[NOW]].

## Structure

One folder level only: `Properties`, `Tenants`, `Finance`, `Taxes`, `Maintenance`, `Legal`, `Property Management`, `Co-Owners`, plus `_system` (AI rules, templates, scripts) and `_export` (generated). `Archive` only when needed.

## Catalog

Generated by `python3 _system/build_export.py`. Do not edit between the markers.

<!-- catalog:start -->
<!-- catalog:end -->

_Last structural update: {today}_
"""


def _looks_like_cloud_sync(path: Path):
    lowered = str(path).lower()
    return next((m for m in CLOUD_SYNC_MARKERS if m in lowered), None)


def _set_restrictive_permissions(path: Path):
    try:
        if path.is_dir():
            path.chmod(stat.S_IRWXU)  # owner rwx, nobody else
        else:
            path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # owner rw, nobody else
    except (NotImplementedError, PermissionError, OSError):
        pass  # best-effort; some filesystems (notably network/exFAT) reject this


def init_vault(destination: Path, today: str):
    destination = destination.expanduser().resolve()

    try:
        destination.relative_to(REPO_ROOT)
        raise SystemExit(
            f"refusing: {destination} is inside this repository ({REPO_ROOT}). "
            "A real vault must live outside it, see SECURITY.md.")
    except ValueError:
        pass  # not inside REPO_ROOT, which is what we want

    if destination.exists() and any(destination.iterdir()):
        raise SystemExit(f"refusing: {destination} already exists and is not empty.")

    if destination.is_symlink():
        raise SystemExit(f"refusing: {destination} is a symlink. Use its real path.")

    cloud_hit = _looks_like_cloud_sync(destination)
    if cloud_hit:
        print(f"WARNING: '{cloud_hit}' appears in the destination path. If this folder "
              f"syncs to a cloud provider, this vault's data will leave your machine. "
              f"See SECURITY.md's security model before continuing.", file=sys.stderr)

    destination.mkdir(parents=True, exist_ok=True)
    _set_restrictive_permissions(destination)

    for rel in DIRS:
        d = destination / rel
        d.mkdir(parents=True, exist_ok=True)
        _set_restrictive_permissions(d)

    for name in ("AGENTS.md", "CLAUDE.md"):
        src = REPO_ROOT / name
        dst = destination / name
        dst.write_text(_restamp_dates(src.read_text(encoding="utf-8"), today),
                        encoding="utf-8")
        _set_restrictive_permissions(dst)

    for name in SCRIPT_FILES:
        src = SYSTEM_SRC / name
        dst = destination / "_system" / name
        text = src.read_text(encoding="utf-8")
        if name.endswith(".md"):
            text = _restamp_dates(text, today)
        dst.write_text(text, encoding="utf-8")
        _set_restrictive_permissions(dst)

    (destination / "NOW.md").write_text(FRESH_NOW_MD.format(today=today), encoding="utf-8")
    (destination / "_index.md").write_text(FRESH_INDEX_MD.format(today=today), encoding="utf-8")
    for name in ("NOW.md", "_index.md"):
        _set_restrictive_permissions(destination / name)

    marker = destination / ".sensitive-vault"
    marker.write_text(MARKER_CONTENT, encoding="utf-8")
    _set_restrictive_permissions(marker)

    return destination


def validate(destination: Path):
    problems = []
    if not (destination / ".sensitive-vault").exists():
        problems.append("missing .sensitive-vault marker")
    for rel in DIRS:
        if not (destination / rel).is_dir():
            problems.append(f"missing directory: {rel}")
    for name in ("AGENTS.md", "CLAUDE.md", "NOW.md", "_index.md"):
        if not (destination / name).is_file():
            problems.append(f"missing file: {name}")
    for name in SCRIPT_FILES:
        if not (destination / "_system" / name).is_file():
            problems.append(f"missing file: _system/{name}")
    return problems


def main(argv=None):
    import datetime

    ap = argparse.ArgumentParser(
        description="Creates a new, empty private vault outside this repository.")
    ap.add_argument("--destination", required=True,
                     help="Where to create the new vault. Must not exist yet, "
                          "or must be empty, and must be outside this repository.")
    args = ap.parse_args(argv)

    today = datetime.date.today().isoformat()
    try:
        destination = init_vault(Path(args.destination), today)
    except SystemExit as e:
        print(str(e), file=sys.stderr)
        return 2

    problems = validate(destination)
    if problems:
        print("Initialization finished but validation found problems:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 2

    print(f"Vault created at {destination}")
    print("Next steps:")
    print(f"  1. Edit {destination / '_index.md'} to describe your own portfolio.")
    print(f"  2. Add your first Properties/, Tenants/, and Finance/ notes.")
    print(f"  3. Run: python3 {destination / '_system' / 'lint.py'} --vault {destination}")
    print("No git repository was created. See SECURITY.md if you want version history.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
